-- 102 — Que una plantilla se pueda construir ENTERA y sus huecos salgan de Orbit
--
-- La 097 dejó el mapeo {{n}} → dato de Orbit, pero solo para huecos NUMERADOS y
-- solo en el cuerpo y el botón. Contra la API real (probado 2026-08-19 con la
-- WABA 596644673438490) resultó que Meta permite bastante más de lo que el
-- módulo sabía hacer:
--
--   • Variables CON NOMBRE (`parameter_format: NAMED`): `{{mascota}}` en vez de
--     `{{1}}`. Cambia todo para el mapeo: el hueco ya dice qué es, y reordenar
--     el texto deja de desalinear los datos.
--   • Cabecera con IMAGEN / VIDEO / PDF. Sí se puede: no con una URL —eso da
--     `error_subcode 2388273`, que fue lo que hizo creer que era imposible—
--     sino subiendo el archivo antes por la Resumable Upload API y mandando el
--     `header_handle` que devuelve.
--   • **Editar una plantilla ya APROBADA** (`POST /{template_id}`) →
--     `{"success":true}`. No hay que borrarla y recrearla.
--
-- Esta migración añade lo que falta en la base para soportar todo eso:
--   1. `param` — el nombre del hueco cuando la plantilla es NAMED.
--   2. `whatsapp_plantilla_cabecera` — qué archivo acompaña a una cabecera de
--      imagen/video/documento AL ENVIAR. Meta obliga a mandar el medio en cada
--      envío (el del alta solo sirvió para la revisión), así que sin esto una
--      plantilla con cabecera de imagen se puede crear pero no se puede usar.

BEGIN;

-- ── 1. Huecos con nombre ────────────────────────────────────────────────────
-- Un hueco es O numerado O con nombre, nunca los dos: `parameter_format` es de
-- la plantilla entera, no de cada variable.
ALTER TABLE public.whatsapp_plantilla_variables
  ADD COLUMN IF NOT EXISTS param text;

-- La PK vieja era (plantilla, idioma, destino, posicion). Se quita PRIMERO: una
-- columna que está en la clave primaria no puede volverse nula (y con huecos
-- con nombre no hay `posicion`). En su lugar va una clave sustituta más un
-- índice único que trata los dos tipos de hueco por igual.
ALTER TABLE public.whatsapp_plantilla_variables
  DROP CONSTRAINT IF EXISTS whatsapp_plantilla_variables_pkey;

ALTER TABLE public.whatsapp_plantilla_variables
  ALTER COLUMN posicion DROP NOT NULL;

ALTER TABLE public.whatsapp_plantilla_variables
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE public.whatsapp_plantilla_variables
  DROP CONSTRAINT IF EXISTS whatsapp_plantilla_variables_hueco_chk;
ALTER TABLE public.whatsapp_plantilla_variables
  ADD CONSTRAINT whatsapp_plantilla_variables_hueco_chk
  CHECK ((posicion IS NULL) <> (param IS NULL));

CREATE UNIQUE INDEX IF NOT EXISTS whatsapp_plantilla_variables_hueco_uq
  ON public.whatsapp_plantilla_variables
     (plantilla, idioma, destino, COALESCE(param, posicion::text));

COMMENT ON COLUMN public.whatsapp_plantilla_variables.param IS
  'Nombre del hueco cuando la plantilla usa parameter_format NAMED ({{mascota}}). Excluyente con `posicion`.';

-- ── 2. El archivo de una cabecera de imagen/video/documento ──────────────────
-- Se apunta al catálogo de materiales (migración 101) en vez de guardar bytes
-- aquí: el brochure ya vive ahí, y tenerlo dos veces garantiza que un día uno
-- de los dos sea el viejo. `url` es la salida para lo que no es un material
-- (una imagen de campaña de una sola vez).
CREATE TABLE IF NOT EXISTS public.whatsapp_plantilla_cabecera (
  plantilla       text NOT NULL,
  idioma          text NOT NULL DEFAULT 'es_MX',
  material_id     bigint REFERENCES public.whatsapp_materiales(id) ON DELETE SET NULL,
  url             text,
  actualizado_en  timestamptz NOT NULL DEFAULT now(),
  actualizado_por uuid REFERENCES public.personal(id) ON DELETE SET NULL,
  PRIMARY KEY (plantilla, idioma),
  CONSTRAINT whatsapp_plantilla_cabecera_origen_chk
    CHECK (material_id IS NOT NULL OR NULLIF(TRIM(url), '') IS NOT NULL)
);

COMMENT ON TABLE public.whatsapp_plantilla_cabecera IS
  'Qué archivo va en la cabecera de imagen/video/documento de una plantilla AL ENVIARLA. Meta exige el medio en cada envío.';

-- ── Permisos ────────────────────────────────────────────────────────────────
-- El rol del backend es `orbit_backend`, NO `postgres`. Sin este GRANT el
-- backend falla en silencio.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.whatsapp_plantilla_cabecera TO orbit_backend;

-- La pantalla pasa por el backend, no por PostgREST.
REVOKE ALL ON TABLE public.whatsapp_plantilla_cabecera FROM anon, authenticated;

COMMIT;
