-- 116 — Carruseles configurables y plantillas autorizadas por agente.
--
-- Meta guarda la definición de la plantilla, pero al ENVIAR un carrusel exige
-- otra vez el medio de cada tarjeta. Orbit conserva la referencia al catálogo
-- de materiales; nunca duplica el binario ni guarda credenciales de WhatsApp.

BEGIN;

-- Los mapeos existentes también necesitan dueño. Dos WABA pueden tener una
-- plantilla con el mismo nombre y no pueden compartir variables ni archivos.
ALTER TABLE public.whatsapp_plantilla_variables
  ADD COLUMN IF NOT EXISTS agente_id integer REFERENCES public.agente_wa(id) ON DELETE CASCADE;

UPDATE public.whatsapp_plantilla_variables
   SET agente_id = (SELECT id FROM public.agente_wa WHERE clave = 'VETERINARIAS')
 WHERE agente_id IS NULL;

ALTER TABLE public.whatsapp_plantilla_variables
  DROP CONSTRAINT IF EXISTS whatsapp_plantilla_variables_destino_check;
ALTER TABLE public.whatsapp_plantilla_variables
  ADD CONSTRAINT whatsapp_plantilla_variables_destino_check CHECK (
    destino IN ('BODY','HEADER','BUTTON')
    OR destino ~ '^CARD:[0-9]+:(BODY|BUTTON:[0-9]+)$'
  );

DROP INDEX IF EXISTS public.whatsapp_plantilla_variables_hueco_uq;
CREATE UNIQUE INDEX whatsapp_plantilla_variables_hueco_uq
  ON public.whatsapp_plantilla_variables
     (agente_id, plantilla, idioma, destino, COALESCE(param, posicion::text))
  NULLS NOT DISTINCT;

ALTER TABLE public.whatsapp_plantilla_cabecera
  ADD COLUMN IF NOT EXISTS agente_id integer REFERENCES public.agente_wa(id) ON DELETE CASCADE;

UPDATE public.whatsapp_plantilla_cabecera
   SET agente_id = (SELECT id FROM public.agente_wa WHERE clave = 'VETERINARIAS')
 WHERE agente_id IS NULL;

ALTER TABLE public.whatsapp_plantilla_cabecera
  DROP CONSTRAINT IF EXISTS whatsapp_plantilla_cabecera_pkey;
ALTER TABLE public.whatsapp_plantilla_cabecera
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

CREATE UNIQUE INDEX IF NOT EXISTS whatsapp_plantilla_cabecera_agente_uq
  ON public.whatsapp_plantilla_cabecera (agente_id, plantilla, idioma)
  NULLS NOT DISTINCT;

-- Un registro por tarjeta. `card_index` es cero-basado porque así lo pide la
-- Cloud API y así aparece en el payload aprobado por Meta.
CREATE TABLE IF NOT EXISTS public.whatsapp_plantilla_tarjetas (
  agente_id      integer NOT NULL REFERENCES public.agente_wa(id) ON DELETE CASCADE,
  plantilla      text NOT NULL,
  idioma         text NOT NULL DEFAULT 'es_MX',
  card_index     integer NOT NULL CHECK (card_index BETWEEN 0 AND 9),
  material_id    bigint REFERENCES public.whatsapp_materiales(id) ON DELETE SET NULL,
  url            text,
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_por uuid REFERENCES public.personal(id) ON DELETE SET NULL,
  PRIMARY KEY (agente_id, plantilla, idioma, card_index),
  CONSTRAINT whatsapp_plantilla_tarjetas_origen_chk CHECK (
    material_id IS NOT NULL OR NULLIF(TRIM(url), '') IS NOT NULL
  )
);

COMMENT ON TABLE public.whatsapp_plantilla_tarjetas IS
  'Medio que se vuelve a subir al enviar cada tarjeta de un carrusel aprobado.';

-- Lista blanca: una plantilla puede existir en la WABA sin que el modelo tenga
-- permiso para usarla. La clave es estable y es la que ve el agente.
CREATE TABLE IF NOT EXISTS public.agente_wa_plantillas (
  id          serial PRIMARY KEY,
  agente_id   integer NOT NULL REFERENCES public.agente_wa(id) ON DELETE CASCADE,
  clave       text NOT NULL CHECK (clave ~ '^[A-Z][A-Z0-9_]{2,49}$'),
  plantilla   text NOT NULL,
  idioma      text NOT NULL DEFAULT 'es_MX',
  descripcion text,
  activa      boolean NOT NULL DEFAULT true,
  orden       integer NOT NULL DEFAULT 0,
  creado_en   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (agente_id, clave),
  UNIQUE (agente_id, plantilla, idioma)
);

-- Solo Veterinarias recibe la capacidad en esta primera entrega. Aunque esté
-- encendida, no se ofrece al modelo hasta que haya una plantilla APROBADA y
-- añadida expresamente a la lista blanca anterior.
INSERT INTO public.agente_wa_herramientas (agente_id, clave, activa, orden)
SELECT id, 'enviar_plantilla', true, 6
  FROM public.agente_wa WHERE clave = 'VETERINARIAS'
ON CONFLICT (agente_id, clave) DO UPDATE SET activa = true;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.whatsapp_plantilla_tarjetas TO orbit_backend;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.agente_wa_plantillas TO orbit_backend;
GRANT USAGE, SELECT ON SEQUENCE public.agente_wa_plantillas_id_seq TO orbit_backend;
GRANT USAGE, SELECT ON SEQUENCE public.whatsapp_plantilla_cabecera_id_seq TO orbit_backend;

REVOKE ALL ON TABLE public.whatsapp_plantilla_tarjetas FROM anon, authenticated;
REVOKE ALL ON TABLE public.agente_wa_plantillas FROM anon, authenticated;

COMMIT;
